default:
  golem_name: nhp.elicitation.tool
  golem_version: 0.0.0.9000
  app_prod: no
  range:
    low: -10
    high: 10
  group: "team_a"
  strategies:
    thf:
      a_productivity:
        name: "Annual productivity rate" 
        label: "Questions"
        min_year: 2013
production:
  app_prod: yes
dev:
  golem_wd: !expr golem::pkg_path()
